name: InfectedV2
version: '1.0-PROTOTYPE'
main: org.nokoshizen.infectedV2.InfectedV2
api-version: '1.21'
depend: [LibsDisguises]
commands:
  points:
    description: Commande opérateur pour se give des points.
  changestats:
    description: Commande opérateur pour changer les stats.
  changekb:
    description: Commande opérateur pour changer le kb.
